# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nokia/sand/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/nokia/sand/proprietary/bin/led_deamon:system/bin/led_deamon \
    vendor/nokia/sand/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/nokia/sand/proprietary/bin/sensord:system/bin/sensord \
    vendor/nokia/sand/proprietary/bin/thermald:system/bin/thermald \
    vendor/nokia/sand/proprietary/etc/firmware/dxhdcp2.b00:system/etc/firmware/dxhdcp2.b00 \
    vendor/nokia/sand/proprietary/etc/firmware/dxhdcp2.b01:system/etc/firmware/dxhdcp2.b01 \
    vendor/nokia/sand/proprietary/etc/firmware/dxhdcp2.b02:system/etc/firmware/dxhdcp2.b02 \
    vendor/nokia/sand/proprietary/etc/firmware/dxhdcp2.b03:system/etc/firmware/dxhdcp2.b03 \
    vendor/nokia/sand/proprietary/etc/firmware/dxhdcp2.flist:system/etc/firmware/dxhdcp2.flist \
    vendor/nokia/sand/proprietary/etc/firmware/dxhdcp2.mdt:system/etc/firmware/dxhdcp2.mdt \
    vendor/nokia/sand/proprietary/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/nokia/sand/proprietary/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/nokia/sand/proprietary/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/nokia/sand/proprietary/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/nokia/sand/proprietary/etc/firmware/tzlibasb.flist:system/etc/firmware/tzlibasb.flist \
    vendor/nokia/sand/proprietary/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/nokia/sand/proprietary/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/nokia/sand/proprietary/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/nokia/sand/proprietary/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/nokia/sand/proprietary/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/nokia/sand/proprietary/etc/firmware/tzsuntory.flist:system/etc/firmware/tzsuntory.flist \
    vendor/nokia/sand/proprietary/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/nokia/sand/proprietary/lib/hw/camera.vendor.msm8960.so:system/lib/hw/camera.vendor.msm8960.so \
    vendor/nokia/sand/proprietary/lib/hw/lights.vendor.msm8960.so:system/lib/hw/lights.vendor.msm8960.so \
    vendor/nokia/sand/proprietary/lib/hw/nfc.msm8960.so:system/lib/hw/nfc.msm8960.so \
    vendor/nokia/sand/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/nokia/sand/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/nokia/sand/proprietary/lib/libchromatix_s5k4e1_2nd_default_video_1.so:system/lib/libchromatix_s5k4e1_2nd_default_video_1.so \
    vendor/nokia/sand/proprietary/lib/libchromatix_s5k4e1_2nd_default_video.so:system/lib/libchromatix_s5k4e1_2nd_default_video.so \
    vendor/nokia/sand/proprietary/lib/libchromatix_s5k4e1_2nd_preview_1.so:system/lib/libchromatix_s5k4e1_2nd_preview_1.so \
    vendor/nokia/sand/proprietary/lib/libchromatix_s5k4e1_2nd_preview.so:system/lib/libchromatix_s5k4e1_2nd_preview.so \
    vendor/nokia/sand/proprietary/lib/libchromatix_s5k4e1_default_video_1.so:system/lib/libchromatix_s5k4e1_default_video_1.so \
    vendor/nokia/sand/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/nokia/sand/proprietary/lib/libchromatix_s5k4e1_preview_1.so:system/lib/libchromatix_s5k4e1_preview_1.so \
    vendor/nokia/sand/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/nokia/sand/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_3a_legacy.so:system/lib/libmmcamera_3a_legacy.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_imx091.so:system/lib/libmmcamera_imx091.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/nokia/sand/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/nokia/sand/proprietary/lib/libmorpho_denoiser.so:system/lib/libmorpho_denoiser.so \
    vendor/nokia/sand/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/nokia/sand/proprietary/lib/libmorpho_edit_engine.so:system/lib/libmorpho_edit_engine.so \
    vendor/nokia/sand/proprietary/lib/libmorpho_fdw.so:system/lib/libmorpho_fdw.so \
    vendor/nokia/sand/proprietary/lib/libmorpho_hdr_checker.so:system/lib/libmorpho_hdr_checker.so \
    vendor/nokia/sand/proprietary/lib/libmorpho_image_stabilizer3.so:system/lib/libmorpho_image_stabilizer3.so \
    vendor/nokia/sand/proprietary/lib/libmorpho_object_tracker2.so:system/lib/libmorpho_object_tracker2.so \
    vendor/nokia/sand/proprietary/lib/libmorpho_posture_detect.so:system/lib/libmorpho_posture_detect.so \
    vendor/nokia/sand/proprietary/lib/libmorpho_scene_detector.so:system/lib/libmorpho_scene_detector.so \
    vendor/nokia/sand/proprietary/lib/libmorpho_super_resolution.so:system/lib/libmorpho_super_resolution.so \
    vendor/nokia/sand/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/nokia/sand/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so

ifeq ($(QCPATH),)
PRODUCT_COPY_FILES += \
    vendor/nokia/sand/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/nokia/sand/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/nokia/sand/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/nokia/sand/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/nokia/sand/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/nokia/sand/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/nokia/sand/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/nokia/sand/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/nokia/sand/proprietary/bin/rild:system/bin/rild \
    vendor/nokia/sand/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/nokia/sand/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/nokia/sand/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/nokia/sand/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/nokia/sand/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/nokia/sand/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/nokia/sand/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/nokia/sand/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/nokia/sand/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/nokia/sand/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/nokia/sand/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/nokia/sand/proprietary/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/nokia/sand/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/nokia/sand/proprietary/lib/libadsprpc.so:system/lib/libadsprpc.so \
    vendor/nokia/sand/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/nokia/sand/proprietary/lib/lib_dlb_msd.so:system/lib/lib_dlb_msd.so \
    vendor/nokia/sand/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/nokia/sand/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/nokia/sand/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/nokia/sand/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/nokia/sand/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/nokia/sand/proprietary/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
    vendor/nokia/sand/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/nokia/sand/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/nokia/sand/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/nokia/sand/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/nokia/sand/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/nokia/sand/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/nokia/sand/proprietary/lib/libmercury.so:system/lib/libmercury.so \
    vendor/nokia/sand/proprietary/lib/libmm-audio-resampler.so:system/lib/libmm-audio-resampler.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_tintless_algo.so:system/lib/libmmcamera_tintless_algo.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_tintless_wrapper.so:system/lib/libmmcamera_tintless_wrapper.so \
    vendor/nokia/sand/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/nokia/sand/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/nokia/sand/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/nokia/sand/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/nokia/sand/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/nokia/sand/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/nokia/sand/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/nokia/sand/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/nokia/sand/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/nokia/sand/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/nokia/sand/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/nokia/sand/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/nokia/sand/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/nokia/sand/proprietary/lib/libqminvapi.so:system/lib/libqminvapi.so \
    vendor/nokia/sand/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/nokia/sand/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/nokia/sand/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/nokia/sand/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/nokia/sand/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/nokia/sand/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/nokia/sand/proprietary/lib/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so \
    vendor/nokia/sand/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/nokia/sand/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/nokia/sand/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/nokia/sand/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/nokia/sand/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/nokia/sand/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/nokia/sand/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/nokia/sand/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/nokia/sand/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/nokia/sand/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/nokia/sand/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/nokia/sand/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/nokia/sand/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/nokia/sand/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/nokia/sand/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/nokia/sand/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/nokia/sand/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/nokia/sand/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/nokia/sand/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/nokia/sand/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/nokia/sand/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/nokia/sand/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/nokia/sand/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/nokia/sand/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/nokia/sand/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/nokia/sand/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/nokia/sand/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/nokia/sand/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/nokia/sand/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/nokia/sand/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/nokia/sand/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/nokia/sand/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/nokia/sand/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so \
    vendor/nokia/sand/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/nokia/sand/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/nokia/sand/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/nokia/sand/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/nokia/sand/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

PRODUCT_PACKAGES += \
    TimeService \
    com.google.widevine.software.drm
endif
